 'use client';
import {useEffect,useState} from 'react';
import './chief.css';
import ProjectItems from './project-items';
import type {ProjectItem} from '../project-products';
type Project={id:number;client:string;phone:string;createdAt:string;items:ProjectItem[]};
const number=(id:number)=>'Ц-'+String(id).padStart(6,'0');
const icons=[<path key="a" d="M5 4h14v16H5zM9 9h6M9 13h6"/>,<path key="b" d="M3 7h7l2 2h9v11H3zM3 7V4h7l2 3"/>,<path key="c" d="M4 20V12m8 8V4m8 16V8"/>,<path key="d" d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 3v2m0 14v2M3 12h2m14 0h2M5.5 5.5 7 7m10 10 1.5 1.5M5.5 18.5 7 17M17 7l1.5-1.5"/>];
export default function Chief(){
 const [authorized,setAuthorized]=useState(false),[projects,setProjects]=useState<Project[]>([]),[page,setPage]=useState('Заказы'),[loading,setLoading]=useState(true),[draft,setDraft]=useState(false),[client,setClient]=useState(''),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[q,setQ]=useState(''),[dark,setDark]=useState(false);
 useEffect(()=>{try{setDark(localStorage.getItem('jevon_chief_dark')==='1')}catch{}fetch('/api/auth',{cache:'no-store'}).then(r=>r.json() as Promise<{department?:string}>).then(a=>{if(a.department!=='Начальник цеха'){window.location.replace('/');return}setAuthorized(true);return fetch('/api/projects',{cache:'no-store'}).then(async r=>{const d=await r.json() as {error?:string;projects:Project[]};if(!r.ok)throw Error(d.error);setProjects(d.projects)})}).catch(e=>setError(e.message||'Не удалось загрузить проекты')).finally(()=>setLoading(false))},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client,phone})}),d=await r.json() as {error?:string;project:Project};if(!r.ok)throw Error(d.error);setProjects(old=>[d.project,...old]);setDraft(false);setClient('');setPhone('');setPage('Проекты')}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить')}finally{setBusy(false)}}
 if(!authorized)return <main className="chief-shell"><p>{error||'Открываем кабинет…'}</p></main>;
 const shown=projects.filter(p=>(number(p.id)+' '+p.client+' '+p.phone).toLowerCase().includes(q.toLowerCase()));
 return <div className={'chief-app'+(dark?' chief-dark':'')}><header className="chief-header"><div><strong>JEVON</strong><span>Кабинет начальника цеха</span></div><span className="chief-role">Заказы цеха</span></header><main className="chief-shell"><div className="chief-title"><div><span className="chief-eyebrow">Управление проектами</span><h1>{page}</h1></div>{(page==='Заказы'||page==='Проекты')&&<button className="chief-primary" onClick={()=>{setDraft(true);setError('')}}>+ Добавить карточку проекта</button>}</div>
 {draft&&<form className="chief-card chief-form" onSubmit={save}><h2>Новый проект</h2><div className="chief-id-note">Номер Ц-000001 присваивается автоматически и не повторяется.</div><label>Имя клиента<input autoFocus required maxLength={120} value={client} onChange={e=>setClient(e.target.value)} placeholder="Имя клиента"/></label><label>Телефон клиента<input required type="tel" inputMode="tel" maxLength={24} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+992… или +7…"/></label><div className="chief-actions"><button disabled={busy} className="chief-primary">{busy?'Сохраняем…':'Сохранить проект'}</button><button disabled={busy} type="button" onClick={()=>{if((client||phone)&&!window.confirm('Закрыть без сохранения? Введённые данные будут потеряны.'))return;setDraft(false);setClient('');setPhone('');setError('')}}>Отмена</button></div></form>}
 {error&&<p role="alert" className="chief-error">{error}</p>}
 {(page==='Заказы'||page==='Проекты')&&<><input className="chief-search" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Номер проекта, клиент или телефон" aria-label="Поиск проекта"/>{loading?<p>Загружаем проекты…</p>:shown.length?<div className="chief-projects">{shown.map(p=><details className="chief-card chief-project" key={p.id}><summary><div><small>Проект цеха</small><h2>{number(p.id)}</h2><strong>{p.client}</strong></div><span className="chief-badge">Создан</span></summary><div className="chief-project-body"><div><span>Телефон клиента</span><a href={'tel:'+p.phone}>{p.phone}</a></div><div><span>Дата создания</span><strong>{new Date(p.createdAt).toLocaleDateString('ru-RU',{timeZone:'Asia/Dushanbe'})}</strong></div><ProjectItems projectId={p.id} items={p.items||[]} onAdd={item=>setProjects(old=>old.map(project=>project.id===p.id?{...project,items:[...(project.items||[]),item]}:project))}/></div></details>)}</div>:<section className="chief-card chief-empty"><h2>{q?'Проекты не найдены':'Первый проект начинается здесь'}</h2><p>{q?'Попробуйте другое имя или номер.':'Создайте карточку с именем и телефоном клиента. Номер проекта сайт присвоит автоматически.'}</p></section>}</>}
 {page==='Статистика'&&<><section className="chief-card chief-stat"><span>Создано проектов</span><strong>{projects.length}</strong></section><section className="chief-card"><h2>Проекты по месяцам</h2>{projects.length?Object.entries(projects.reduce<Record<string,number>>((acc,p)=>{const m=new Date(p.createdAt).toLocaleDateString('ru-RU',{month:'long',year:'numeric',timeZone:'Asia/Dushanbe'});acc[m]=(acc[m]||0)+1;return acc},{})).map(([month,count])=><div className="chief-month" key={month}><span>{month}</span><strong>{count}</strong></div>):<p>Статистика появится после создания первого проекта.</p>}<p className="chief-note">Расходы и прибыль появятся после добавления изделий и финансового учёта.</p></section></>}
 {page==='Настройки'&&<section className="chief-card"><h2>Кабинет начальника цеха</h2><div className="chief-setting"><span>Тема сайта</span><button onClick={()=>setDark(old=>{try{localStorage.setItem('jevon_chief_dark',old?'0':'1')}catch{}return !old})}>{dark?'Тёмная':'Светлая'}</button></div><button onClick={async()=>{await fetch('/api/auth',{method:'DELETE'});window.location.replace('/')}}>Выйти из кабинета</button></section>}
 </main><nav className="chief-nav" aria-label="Разделы кабинета">{['Заказы','Проекты','Статистика','Настройки'].map((p,i)=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)} aria-current={page===p?'page':undefined}><svg viewBox="0 0 24 24" aria-hidden="true">{icons[i]}</svg><span>{p}</span></button>)}</nav></div>
}
