 'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {projectProductTypes,parsePrice,type ProjectItem} from '../project-products';
export const money=(cents:number)=>(cents/100).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})+' с';
export default function ProjectItems({projectId,items,onAdd}:{projectId:number;items:ProjectItem[];onAdd:(item:ProjectItem)=>void}){
 const [adding,setAdding]=useState(false),[name,setName]=useState(''),[quantity,setQuantity]=useState('1'),[price,setPrice]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const dirty=adding&&!!(name||price||quantity!=='1');
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 async function save(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/project-items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,name,quantity:Number(quantity),price})}),data=await response.json() as {item:ProjectItem;error?:string};if(!response.ok)throw Error(data.error);onAdd(data.item);setName('');setQuantity('1');setPrice('');setAdding(false)}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить изделие')}finally{setBusy(false)}}
 const total=items.reduce((sum,item)=>sum+item.quantity*item.unitPriceCents,0),preview=parsePrice(price);
 return <section className="chief-items"><div className="chief-items-heading"><h3>Изделия <small>{items.length}</small></h3><button type="button" className="chief-primary" onClick={()=>setAdding(true)}>+ Добавить изделие</button></div>
 {adding&&<form onSubmit={save} className="chief-item-form"><label>Изделие<select required value={name} onChange={e=>setName(e.target.value)}><option value="">Выберите изделие</option>{projectProductTypes.map(type=><option key={type}>{type}</option>)}</select></label><div className="chief-item-fields"><label>Количество<input required type="number" inputMode="numeric" min="1" max="9999" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Цена за единицу, сомони<input required type="text" inputMode="decimal" placeholder="Например: 20000,50" pattern="[0-9]{1,8}([.,][0-9]{1,2})?" value={price} onChange={e=>setPrice(e.target.value)}/></label></div><div className="chief-item-preview">Сумма <strong>{preview===null||!Number.isInteger(Number(quantity))||Number(quantity)<1?'—':money(preview*Number(quantity))}</strong></div>{error&&<p className="chief-error" role="alert">{error}</p>}<div className="chief-actions"><button className="chief-primary" disabled={busy}>{busy?'Сохраняем…':'Сохранить изделие'}</button><button type="button" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Закрыть без сохранения изделия?'))return;setAdding(false);setName('');setQuantity('1');setPrice('');setError('')}}>Отмена</button></div></form>}
 {items.length?<div className="chief-items-list">{items.map(item=><details key={item.id} className="chief-item"><summary><div><strong>{item.name}</strong><small>{item.quantity} шт. × {money(item.unitPriceCents)}</small></div><b>{money(item.quantity*item.unitPriceCents)}</b></summary><div className="chief-item-detail"><span>Номер изделия</span><strong>{'Ц-'+String(projectId).padStart(6,'0')+'-'+String(item.id).padStart(3,'0')}</strong><span>Количество</span><strong>{item.quantity} шт.</strong><span>Цена за единицу</span><strong>{money(item.unitPriceCents)}</strong><span>Сумма изделия</span><strong>{money(item.quantity*item.unitPriceCents)}</strong></div></details>)}</div>:<p className="chief-note">Изделия ещё не добавлены. Выберите их из списка и укажите количество и цену.</p>}
 <div className="chief-project-total"><span>Общая стоимость проекта</span><strong>{money(total)}</strong></div></section>
}
