'use client';
import {useState} from 'react';
export type PortalUser={id:number;username:string;fullName:string;role:'admin'|'analyst';active:boolean;employeeId:number|null};
type Employee={id:number;name:string;department:string};
export default function UsersForm({initialUsers,employees}:{initialUsers:PortalUser[];employees:Employee[]}){
 const [users,setUsers]=useState(initialUsers),[username,setUsername]=useState(''),[fullName,setFullName]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('analyst'),[employeeId,setEmployeeId]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function submit(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/reports/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,fullName,password,role,employeeId:employeeId?Number(employeeId):null})});const data=await r.json() as {user:PortalUser;error?:string};if(!r.ok)throw Error(data.error);setUsers(old=>[...old,data.user]);setPassword('');setUsername('');setFullName('');setEmployeeId('');setRole('analyst');setMessage('Пользователь создан. Он может войти своим логином и паролем.')}catch(e){setError(e instanceof Error?e.message:'Не удалось создать пользователя.')}finally{setBusy(false)}}
 return <><h2 className="text-xl font-bold">Создание пользователя</h2><form onSubmit={submit} className="grid gap-4 rounded-xl border-border bg-card text-card-foreground p-5 sm:grid-cols-2"><label>Логин<input required pattern="[a-zA-Z0-9_.@-]{3,80}" minLength={3} maxLength={80} autoComplete="off" value={username} onChange={e=>setUsername(e.target.value)} className="mt-1 block w-full rounded border border-input bg-background text-foreground p-2"/></label><label>Имя<input required maxLength={120} value={fullName} onChange={e=>setFullName(e.target.value)} className="mt-1 block w-full rounded border border-input bg-background text-foreground p-2"/></label><label>Пароль (минимум 12 символов)<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 block w-full rounded border border-input bg-background text-foreground p-2"/></label><label>Роль<select value={role} onChange={e=>setRole(e.target.value)} className="mt-1 block w-full rounded border border-input bg-background text-foreground p-2"><option value="analyst">Аналитик — просмотр отчётов</option><option value="admin">Администратор — отчёты и пользователи</option></select></label><label>Сотрудник<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} className="mt-1 block w-full rounded border border-input bg-background text-foreground p-2"><option value="">Без привязки</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.department}</option>)}</select></label><div className="flex items-end"><button disabled={busy} className="rounded bg-slate-800 px-5 py-2 text-white disabled:opacity-50">{busy?'Сохранение…':'Создать пользователя'}</button></div></form>{error&&<p role="alert" className="text-red-600">{error}</p>}{message&&<p role="status" className="text-green-700">{message}</p>}<h2 className="text-xl font-bold">Пользователи портала</h2><table className="w-full text-left"><thead><tr><th>Логин</th><th>Имя</th><th>Роль</th><th>Сотрудник</th><th>Статус</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.fullName}</td><td>{u.role==='admin'?'Администратор':'Аналитик'}</td><td>{employees.find(e=>e.id===u.employeeId)?.name??'—'}</td><td>{u.active?'Активен':'Отключён'}</td></tr>)}</tbody></table></>;
}
