"use client";
import {useState} from 'react';
type Employee={id:number;name:string;department:string;active:boolean};
type Event={id:number;name:string;department:string;action:string;photoKey:string;createdAt:string};
export default function EmployeesPage(){
 const [pin,setPin]=useState(''),[message,setMessage]=useState(''),[employees,setEmployees]=useState<Employee[]>([]),[events,setEvents]=useState<Event[]>([]),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false);
 const [name,setName]=useState(''),[department,setDepartment]=useState(''),[code,setCode]=useState('');
 async function refresh(){const [a,b]=await Promise.all([fetch('/api/employees'),fetch('/api/attendance')]);if(!a.ok||!b.ok)throw Error('Войдите кодом менеджера или начальника цеха.');setEmployees(((await a.json()) as {employees:Employee[]}).employees);setEvents(((await b.json()) as {events:Event[]}).events);setLoaded(true)}
 async function login(){setBusy(true);setMessage('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});if(!r.ok)throw Error('Не удалось войти. Проверьте код.');setPin('');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Ошибка сети')}finally{setBusy(false)}}
 async function add(){setBusy(true);setMessage('');try{const r=await fetch('/api/employees',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,department,code})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);setName('');setDepartment('');setCode('');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Ошибка сети')}finally{setBusy(false)}}
 return <main className="mx-auto max-w-6xl space-y-6 p-6"><h1 className="text-2xl font-bold">Сотрудники и посещаемость</h1>{message&&<p role="alert" className="text-red-600">{message}</p>}{!loaded?<div className="flex flex-wrap gap-3"><input aria-label="Код руководителя" type="password" inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value)} placeholder="Код руководителя" className="rounded border p-2"/><button disabled={busy} onClick={login} className="rounded bg-slate-800 px-4 py-2 text-white">Войти</button></div>:<><div className="flex flex-wrap gap-3"><input aria-label="Имя" value={name} onChange={e=>setName(e.target.value)} placeholder="Имя" className="rounded border p-2"/><input aria-label="Отдел" value={department} onChange={e=>setDepartment(e.target.value)} placeholder="Отдел" className="rounded border p-2"/><input aria-label="Код сотрудника" type="password" inputMode="numeric" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="Код сотрудника" className="rounded border p-2"/><button disabled={busy} onClick={add} className="rounded bg-slate-800 px-4 py-2 text-white">Добавить сотрудника</button><button disabled={busy} onClick={()=>refresh().catch(e=>setMessage(e.message))}>Обновить</button></div><h2 className="text-xl font-bold">Сотрудники</h2><table className="w-full text-left"><thead><tr><th>Имя</th><th>Отдел</th><th>Статус</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.department}</td><td>{e.active?'Активен':'Отключён'}</td></tr>)}</tbody></table><h2 className="text-xl font-bold">Журнал — последние 500 записей</h2>{events.length===0?<p>Записей пока нет.</p>:<table className="w-full text-left"><thead><tr><th>Сотрудник</th><th>Действие</th><th>Время</th><th>Фото</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.action==='IN'?'Приход':'Уход'}</td><td>{new Date(e.createdAt).toLocaleString('ru-RU',{timeZone:'Asia/Dushanbe'})}</td><td><a target="_blank" rel="noreferrer" href={'/api/attendance-photo?key='+encodeURIComponent(e.photoKey)}>Открыть</a></td></tr>)}</tbody></table>}</>}</main>;
}
