CREATE TABLE IF NOT EXISTS archived_deadlines_20260925(
  order_id TEXT,
  deadline TEXT
);

CREATE TABLE IF NOT EXISTS archived_drawings_20260925(
  order_id TEXT,
  completed_at TEXT
);

CREATE TABLE IF NOT EXISTS archived_materials_20260925(
  id INT,
  order_id TEXT,
  type TEXT,
  description TEXT,
  thickness TEXT,
  planned INT,
  received INT,
  condition TEXT,
  note TEXT,
  received_at TEXT,
  photo_key TEXT
);

CREATE TABLE IF NOT EXISTS archived_share_links_20260925(
  order_id TEXT,
  token TEXT
);

CREATE TABLE IF NOT EXISTS archived_shipments_20260925(
  order_id TEXT,
  picked_up_at TEXT
);

CREATE TABLE IF NOT EXISTS archived_stages_20260925(
  order_id TEXT,
  stage TEXT,
  status TEXT
);

CREATE TABLE IF NOT EXISTS "order_acceptances" (
	"order_id" text PRIMARY KEY NOT NULL,
	"accepted_at" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "order_deadlines" (
	"order_id" text PRIMARY KEY NOT NULL,
	"deadline" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "order_drawing_links" (
	"order_id" text PRIMARY KEY NOT NULL,
	"url" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "order_drawings" (
	"order_id" text PRIMARY KEY NOT NULL,
	"completed_at" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "order_estimate_changes" (
	"order_id" text NOT NULL,
	"row_id" text NOT NULL,
	"data" text NOT NULL,
	PRIMARY KEY("order_id", "row_id")
);

CREATE TABLE IF NOT EXISTS "order_materials" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"type" text NOT NULL,
	"description" text NOT NULL,
	"thickness" text NOT NULL,
	"planned" integer NOT NULL,
	"received" integer,
	"condition" text DEFAULT 'Ожидаем' NOT NULL,
	"note" text DEFAULT '' NOT NULL,
	"received_at" text
, "photo_key" text, "supply_source" text DEFAULT 'client' NOT NULL, "purchase_unit_price_cents" integer, "purchase_quantity" integer);

CREATE TABLE IF NOT EXISTS "order_share_links" (
	"order_id" text PRIMARY KEY NOT NULL,
	"token" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "order_shipments" (
	"order_id" text PRIMARY KEY NOT NULL,
	"picked_up_at" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "order_stage_statuses" (
	"order_id" text NOT NULL,
	"stage" text NOT NULL,
	"status" text NOT NULL,
	PRIMARY KEY("order_id", "stage")
);

CREATE TABLE IF NOT EXISTS pin_attempts (ip TEXT PRIMARY KEY, attempts INTEGER NOT NULL, window_start INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS "service_price_overrides" (
	"type" text PRIMARY KEY NOT NULL,
	"price_cents" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "synced_orders" (
	"id" text PRIMARY KEY NOT NULL,
	"data" text NOT NULL,
	"updated_at" text NOT NULL
);



CREATE TABLE IF NOT EXISTS "workshop_projects" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"client" text NOT NULL,
	"phone" text NOT NULL,
	"created_at" text NOT NULL
);
CREATE TABLE IF NOT EXISTS push_subscriptions (endpoint TEXT PRIMARY KEY,role_code TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS stored_files (key TEXT PRIMARY KEY,data BYTEA NOT NULL,content_type TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS employees (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL,department TEXT NOT NULL DEFAULT '',code_hash TEXT UNIQUE NOT NULL,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS attendance_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,employee_id INTEGER NOT NULL REFERENCES employees(id),action TEXT NOT NULL CHECK(action IN ('IN','OUT')),photo_key TEXT NOT NULL REFERENCES stored_files(key),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS attendance_employee_time ON attendance_events(employee_id,created_at DESC,id DESC);
-- SQLite allowed fractional measured quantities in INTEGER columns.
ALTER TABLE order_materials ALTER COLUMN planned TYPE double precision;
ALTER TABLE order_materials ALTER COLUMN received TYPE double precision;
ALTER TABLE order_materials ALTER COLUMN purchase_quantity TYPE double precision;
CREATE UNIQUE INDEX IF NOT EXISTS order_share_links_token_unique ON order_share_links(token);

CREATE TABLE IF NOT EXISTS "workshop_project_items" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"project_id" integer NOT NULL,
	"name" text NOT NULL,
	"quantity" integer NOT NULL,
	"unit_price_cents" integer NOT NULL,
	"created_at" text NOT NULL,
	FOREIGN KEY ("project_id") REFERENCES "workshop_projects"("id") ON UPDATE no action ON DELETE no action
);
