CREATE TABLE reports_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE NOT NULL CHECK (username = lower(username)),
  full_name text NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin','analyst')),
  employee_id integer REFERENCES employees(id) ON DELETE SET NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE reports_sessions (
  token_hash text PRIMARY KEY,
  user_id integer NOT NULL REFERENCES reports_users(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reports_sessions_expiry ON reports_sessions(expires_at);
CREATE TABLE reports_login_attempts (
  ip text PRIMARY KEY,
  attempts integer NOT NULL,
  window_start timestamptz NOT NULL DEFAULT now()
);
