"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, Check, LogIn, LogOut, RefreshCcw, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Action = "IN" | "OUT"; type Step = "action" | "scan" | "code" | "camera" | "preview" | "success";
type QrDetector = {detect:(source:CanvasImageSource)=>Promise<Array<{rawValue:string}>>};
export default function Home() {
 const [step,setStep]=useState<Step>("action"),[action,setAction]=useState<Action|null>(null),[code,setCode]=useState(""),[photoData,setPhotoData]=useState(""),[countdown,setCountdown]=useState<number|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const videoRef=useRef<HTMLVideoElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),streamRef=useRef<MediaStream|null>(null),scanTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);
 const stopCamera=()=>{if(scanTimerRef.current)clearTimeout(scanTimerRef.current);scanTimerRef.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null};
 useEffect(()=>{return()=>stopCamera()},[]);
 const enterFullscreen=async()=>{try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen({navigationUI:"hide"})}catch{}};
 const chooseAction=(next:Action)=>{void enterFullscreen();setAction(next);setMessage("");void startQrScanner()};
 const startQrScanner=async()=>{setMessage("");setCode("");setPhotoData("");setStep("scan");try{stopCamera();const Detector=(window as typeof window&{BarcodeDetector?:new(options:{formats:string[]})=>QrDetector}).BarcodeDetector;if(!Detector)throw new Error("unsupported");const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:960}},audio:false});streamRef.current=stream;await new Promise(r=>setTimeout(r,0));if(!videoRef.current)throw new Error("camera");videoRef.current.srcObject=stream;await videoRef.current.play();const detector=new Detector({formats:["qr_code"]});const scan=async()=>{if(!videoRef.current||!streamRef.current)return;try{const found=await detector.detect(videoRef.current);const raw=found[0]?.rawValue?.trim()||"";const scannedCode=raw.startsWith("JEVON:")?raw.slice(6):raw;if(/^\d{4}$/.test(scannedCode)){setCode(scannedCode);setStep("camera");for(const n of [3,2,1]){setCountdown(n);await new Promise(r=>setTimeout(r,900))}setCountdown(null);capture();return}}catch{}scanTimerRef.current=setTimeout(scan,250)};void scan()}catch{stopCamera();setMessage("QR-сканер дар ин дастгоҳ кушода нашуд. Кодро дастӣ ворид кунед.");setStep("code")}};
 const startCamera=async(enteredCode=code)=>{if(enteredCode.trim().length!==4){setMessage("Коди 4-рақамаро пурра ворид кунед.");return}setMessage("");setPhotoData("");setStep("camera");try{stopCamera();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:960}},audio:false});streamRef.current=stream;if(!videoRef.current)throw new Error("camera");videoRef.current.srcObject=stream;await videoRef.current.play();await new Promise(r=>setTimeout(r,700));for(const n of [3,2,1]){setCountdown(n);await new Promise(r=>setTimeout(r,900))}setCountdown(null);capture()}catch{stopCamera();setCountdown(null);setMessage("Камера кушода нашуд. Ба браузер иҷозати камера диҳед.");setStep("code")}};
 const capture=()=>{const v=videoRef.current,c=canvasRef.current;if(!v||!c)return;const w=v.videoWidth||640,h=v.videoHeight||480;c.width=w;c.height=h;const x=c.getContext("2d");if(!x)return;x.translate(w,0);x.scale(-1,1);x.drawImage(v,0,0,w,h);setPhotoData(c.toDataURL("image/jpeg",.82));stopCamera();setStep("preview")};
 const announce=(text:string)=>{if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(text);speech.lang="tg-TJ";speech.rate=.9;speech.pitch=1;speech.volume=1;const voices=window.speechSynthesis.getVoices();speech.voice=voices.find(v=>v.lang.toLowerCase().startsWith("tg"))||voices.find(v=>v.lang.toLowerCase().startsWith("ru"))||null;window.speechSynthesis.speak(speech)};
 const submit=async()=>{if(!action||!photoData||busy)return;setBusy(true);setMessage("");try{const response=await fetch("/api/attendance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:code.trim(),action,photoData})});const result=await response.json() as {ok?:boolean;message?:string};if(!response.ok||!result.ok)throw new Error(result.message||"Сабт нашуд.");const successMessage=action==="IN"?"Хуш омадед!":"Роҳи сафед!";setMessage(result.message||successMessage);setStep("success");announce(successMessage);setTimeout(reset,2600)}catch(e){setMessage(e instanceof Error?e.message:"Хатогӣ рӯй дод.")}finally{setBusy(false)}};
 const reset=()=>{stopCamera();if("speechSynthesis" in window)window.speechSynthesis.cancel();setAction(null);setCode("");setPhotoData("");setCountdown(null);setMessage("");setStep("action")};
 return <main className="grid min-h-dvh place-items-center bg-[#0e3a5a] p-3 sm:p-6"><section className={`flex w-full flex-col overflow-hidden rounded-[2rem] bg-white shadow-2xl ${step==="action"?"max-w-[700px]":"max-w-[760px]"}`}><header className="border-b border-slate-100 px-6 pb-4 pt-6 text-center sm:px-10 sm:pt-8"><h1 className="text-3xl font-black tracking-tight text-[#0e3a5a] sm:text-4xl">JEVON <span className="font-light">|</span> Ҳасту нест</h1><p className="mt-2 text-lg text-slate-500">{step==="action"&&"Амалро интихоб кунед"}{step==="scan"&&"QR-кодро ба камера нишон диҳед"}{step==="code"&&(action==="IN"?"Омадан ба кор":"Рафтан аз кор")}{step==="camera"&&"Ба камера нигоҳ кунед"}{step==="preview"&&"Суратро тасдиқ кунед"}{step==="success"&&"Қайд бомуваффақият анҷом ёфт"}</p></header><div className="flex flex-col justify-center p-5 sm:p-8">
 {step==="action"&&<div className="grid gap-4"><Button onClick={()=>chooseAction("IN")} className="h-24 w-full rounded-2xl bg-emerald-600 text-2xl font-bold shadow-lg hover:bg-emerald-700 active:scale-[.99]"><LogIn className="mr-3 size-9"/>Ба кор омадам</Button><Button onClick={()=>chooseAction("OUT")} className="h-24 w-full rounded-2xl bg-red-500 text-2xl font-bold shadow-lg hover:bg-red-600 active:scale-[.99]"><LogOut className="mr-3 size-9"/>Аз кор рафтам</Button></div>}
 {step==="code"&&<div className="mx-auto w-full max-w-md"><label htmlFor="worker-code" className="mb-3 block text-center text-lg font-semibold text-slate-700">Коди шахсии худро ворид кунед</label><Input id="worker-code" autoFocus type="password" inputMode="numeric" autoComplete="off" maxLength={4} value={code} onChange={e=>{const next=e.target.value.replace(/\D/g,"").slice(0,4);setCode(next);setMessage("");if(next.length===4)void startCamera(next)}} onKeyDown={e=>e.key==="Enter"&&startCamera()} placeholder="••••" className="h-20 rounded-2xl border-2 text-center text-3xl tracking-[.45em]"/><Button onClick={()=>startCamera()} className="mt-5 h-16 w-full rounded-2xl bg-[#0e3a5a] text-xl font-bold hover:bg-[#0a2e49]"><Camera className="mr-3 size-6"/>Кушодани камера</Button><Button variant="ghost" onClick={reset} className="mt-3 h-12 w-full text-base text-slate-500">← Бозгашт</Button></div>}
 {(step==="scan"||step==="camera"||step==="preview")&&<div className="space-y-5"><div className="relative mx-auto aspect-[4/3] w-full overflow-hidden rounded-[1.5rem] bg-[#06131d] shadow-inner"><video ref={videoRef} autoPlay muted playsInline className={`h-full w-full scale-x-[-1] object-cover ${step==="preview"?"hidden":"block"}`}/>{photoData&&<img src={photoData} alt="Сурати коргар" className="h-full w-full object-cover"/>}{step==="scan"&&<div className="pointer-events-none absolute inset-[14%] rounded-3xl border-4 border-white/90 shadow-[0_0_0_999px_rgba(0,0,0,.28)]"/>}{countdown!==null&&<div className="absolute inset-0 grid place-items-center bg-black/20 text-9xl font-black text-white drop-shadow-lg">{countdown}</div>}</div>{step==="scan"&&<div className="grid gap-2"><p className="text-center text-lg font-semibold text-[#0e3a5a]">QR-кодро дар дохили чорчӯба нигоҳ доред</p><Button variant="ghost" onClick={()=>{stopCamera();setMessage("");setStep("code")}} className="h-12 text-base text-slate-500">Кодро дастӣ ворид кардан</Button><Button variant="ghost" onClick={reset} className="h-12 text-base text-slate-500">← Бозгашт</Button></div>}{step==="preview"&&<div className="grid gap-3 sm:grid-cols-2"><Button variant="secondary" onClick={()=>startCamera()} className="h-16 rounded-2xl text-lg font-bold"><RotateCcw className="mr-2 size-5"/>Аз нав гирифтан</Button><Button onClick={submit} disabled={busy} className="h-16 rounded-2xl bg-emerald-600 text-lg font-bold hover:bg-emerald-700"><Check className="mr-2 size-6"/>{busy?"Сабт шуда истодааст…":"Ба қайд даровардан"}</Button></div>}</div>}
 {step==="success"&&<div className="text-center"><div className="mx-auto grid size-28 place-items-center rounded-full bg-emerald-100 text-emerald-600"><Check className="size-16" strokeWidth={3}/></div><p className="mt-6 text-3xl font-black text-[#0e3a5a]">{message}</p><Button variant="ghost" onClick={reset} className="mt-6"><RefreshCcw className="mr-2 size-4"/>Ба саҳифаи аввал</Button></div>}
 {message&&step!=="success"&&<div className="mt-5 text-center"><p role="alert" className="text-lg font-bold text-red-600">{message}</p>{step==="preview"&&<Button variant="secondary" onClick={reset} className="mt-4 h-14 w-full rounded-2xl text-lg font-normal text-[#0e3a5a] hover:bg-slate-200">← Бозгашт</Button>}</div>}</div></section><canvas ref={canvasRef} hidden/></main>;
}
