import {env} from 'cloudflare:workers';
const secret=()=>(env as unknown as {BRIDGE_SECRET?:string}).BRIDGE_SECRET;
const hex=(bytes:ArrayBuffer)=>Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');
export function normalizePhone(value:unknown){const d=String(value||'').replace(/\D/g,'');return /^\d{9}$/.test(d)?'992'+d:/^(?:992\d{9}|7\d{10})$/.test(d)?d:null}
export async function sign(value:string){if(!secret())throw Error('Session configuration missing');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret()),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))}
export function same(a:string,b:string){let diff=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0}
export async function passwordHash(pin:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:100000},key,256))}
export async function clientPhone(request:Request){const token=request.headers.get('Cookie')?.match(/(?:^|;\s*)jevon_client=([^;]+)/)?.[1];if(!token)return null;const [phone,expiry,sig]=token.split('.');if(!/^(?:992\d{9}|7\d{10})$/.test(phone||'')||!/^\d+$/.test(expiry||'')||Number(expiry)<Date.now()/1000||!sig)return null;const account=await env.DB!.prepare('SELECT salt FROM client_accounts WHERE phone=?').bind(phone).first<{salt:string}>();return account&&same(sig,await sign(phone+'.'+expiry+'.'+account.salt))?phone:null}
export async function sessionCookie(phone:string){const account=await env.DB!.prepare('SELECT salt FROM client_accounts WHERE phone=?').bind(phone).first<{salt:string}>();if(!account)throw Error('Account missing');const value=phone+'.'+Math.floor(Date.now()/1000+12*3600);return `jevon_client=${value}.${await sign(value+'.'+account.salt)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200`}
export class ClientLinkError extends Error { constructor(message:string,public status:number){super(message)} }
export async function syncClientOrders(phone:string|null,token?:string){const response=await fetch('https://jevon-order-status.rajabalisharipov87.chatgpt.site/api/client-orders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${secret()}`},body:JSON.stringify({phone,token})});if(!response.ok){if(response.status===403||response.status===400)throw new ClientLinkError('Телефон не соответствует заказу по этой ссылке либо не заполнен в карточке. Откройте ссылку своего заказа или уточните телефон у менеджера.',403);throw new ClientLinkError('Сервис заказов временно недоступен. Попробуйте позже.',503)}return await response.json() as {phone:string}}
export const noStore={'Cache-Control':'private, no-store'};
